name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
  update-apps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: prepare git
        run: |
          git config --global user.email 'rpm-bot@coder966.net'
          git config --global user.name 'RPM Bot'
      
      - name: postman
        run: |
          ./update.sh postman

      - name: intellij-idea-ultimate
        run: |
          ./update.sh intellij-idea-ultimate

      - name: soapui
        run: |
          ./update.sh soapui

      - name: visualvm
        run: |
          ./update.sh visualvm
